name: Update README with Traffic Stats

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Get Repository Data
        id: repo_data
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:owner/:repo/traffic/views
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Clone Data
        id: clone_data
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:owner/:repo/traffic/clones
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Star Count
        id: stars
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:owner/:repo
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README
        run: |
          VIEWS=${{ steps.repo_data.outputs.data }}
          CLONES=${{ steps.clone_data.outputs.data }}
          STARS=${{ steps.stars.outputs.data }}
          
          sed -i '/<!-- stats start -->/,/<!-- stats end -->/c\<!-- stats start -->\nViews: $VIEWS\nClones: $CLONES\nStars: $STARS\n<!-- stats end -->' README.md
          
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with traffic, clones, and stars"
          git push
